# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NutritionAnalysis' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NutritionAnalysis
  pod 'Moya'
  pod 'MBProgressHUD'
  pod 'Nuke'
  pod 'SwiftLint'
  pod 'SwiftMessages'
  pod 'IQKeyboardManagerSwift'
  target 'NutritionAnalysisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NutritionAnalysisUITests' do
    # Pods for testing
  end

end
